### PR TITLE
Add support for 3.6, drop support for 3.3.

### PR DESCRIPTION
**Pull request by jamadden**
Also enable coverage reporting and universal wheels.

### CODE REVIEW

**Review by mgedmin — APPROVED** [review]
LGTM

**Comment by jamadden** [comment]
Thanks! Could we get a PyPI release (or access to do the same) @tseaver? For zopefoundation/zopetoolkit#8.

**Comment by tseaver** [comment]
I've added `jamadden` as an owner on PyPI.

**Comment by jamadden** [comment]
Thanks! 2.1.0 has been released to PyPI.

**Pull request merged**
